"""
SQLAlchemy ORM models for the Accounting & Legal AI Chatbot.
"""

import uuid
from datetime import datetime, timezone
from sqlalchemy import (
    Column, String, Text, DateTime, Integer, Float, Boolean, ForeignKey, JSON
)
from sqlalchemy.orm import relationship
from db.database import Base


def _utcnow():
    return datetime.now(timezone.utc)


def _new_id():
    return str(uuid.uuid4())


# ═══════════════════════════════════════════════════════════════════
# Chat Models
# ═══════════════════════════════════════════════════════════════════

class Conversation(Base):
    """A chat conversation (thread)."""
    __tablename__ = "conversations"

    id = Column(String(36), primary_key=True, default=_new_id)
    title = Column(String(255), default="New Conversation")
    created_at = Column(DateTime, default=_utcnow)
    updated_at = Column(DateTime, default=_utcnow, onupdate=_utcnow)
    llm_provider = Column(String(50), default="nvidia")
    llm_model = Column(String(100), default="")

    messages = relationship("Message", back_populates="conversation", cascade="all, delete-orphan")


class Message(Base):
    """A single message within a conversation."""
    __tablename__ = "messages"

    id = Column(String(36), primary_key=True, default=_new_id)
    conversation_id = Column(String(36), ForeignKey("conversations.id"), nullable=False)
    role = Column(String(20), nullable=False)  # user | assistant | system
    content = Column(Text, nullable=False)
    sources = Column(JSON, nullable=True)  # RAG source citations
    created_at = Column(DateTime, default=_utcnow)
    tokens_used = Column(Integer, default=0)

    conversation = relationship("Conversation", back_populates="messages")


# ═══════════════════════════════════════════════════════════════════
# Document Models
# ═══════════════════════════════════════════════════════════════════

class Document(Base):
    """An uploaded document indexed for RAG."""
    __tablename__ = "documents"

    id = Column(String(36), primary_key=True, default=_new_id)
    filename = Column(String(500), nullable=False)
    original_name = Column(String(500), nullable=False)
    file_type = Column(String(20), nullable=False)  # pdf | docx | xlsx | txt
    file_size = Column(Integer, default=0)  # bytes
    chunk_count = Column(Integer, default=0)
    status = Column(String(20), default="processing")  # processing | indexed | error
    error_message = Column(Text, nullable=True)
    created_at = Column(DateTime, default=_utcnow)
    metadata_json = Column(JSON, nullable=True)


# ═══════════════════════════════════════════════════════════════════
# Report Models
# ═══════════════════════════════════════════════════════════════════

class GeneratedReport(Base):
    """A financial/tax report generated by the system."""
    __tablename__ = "generated_reports"

    id = Column(String(36), primary_key=True, default=_new_id)
    report_type = Column(String(50), nullable=False)  # ifrs | vat_return | corp_tax
    title = Column(String(255), nullable=False)
    input_data = Column(JSON, nullable=True)
    output_path = Column(String(500), nullable=True)
    status = Column(String(20), default="pending")  # pending | generating | complete | error
    error_message = Column(Text, nullable=True)
    created_at = Column(DateTime, default=_utcnow)


# ═══════════════════════════════════════════════════════════════════
# Monitoring / Alert Models
# ═══════════════════════════════════════════════════════════════════

class MonitoredSource(Base):
    """A website/URL being monitored for regulatory changes."""
    __tablename__ = "monitored_sources"

    id = Column(String(36), primary_key=True, default=_new_id)
    name = Column(String(255), nullable=False)
    url = Column(String(1000), nullable=False)
    category = Column(String(50), default="general")  # law | tax | vat | general
    is_active = Column(Boolean, default=True)
    check_interval_hours = Column(Integer, default=6)
    last_checked = Column(DateTime, nullable=True)
    last_hash = Column(String(64), nullable=True)  # SHA-256 of last content
    created_at = Column(DateTime, default=_utcnow)

    alerts = relationship("Alert", back_populates="source", cascade="all, delete-orphan")


class Alert(Base):
    """A regulatory change alert detected by monitoring."""
    __tablename__ = "alerts"

    id = Column(String(36), primary_key=True, default=_new_id)
    source_id = Column(String(36), ForeignKey("monitored_sources.id"), nullable=False)
    title = Column(String(500), nullable=False)
    summary = Column(Text, nullable=True)
    diff_content = Column(Text, nullable=True)  # What changed
    severity = Column(String(20), default="info")  # info | warning | critical
    is_read = Column(Boolean, default=False)
    created_at = Column(DateTime, default=_utcnow)

    source = relationship("MonitoredSource", back_populates="alerts")


# ═══════════════════════════════════════════════════════════════════
# Settings Model
# ═══════════════════════════════════════════════════════════════════

class UserSettings(Base):
    """Persisted user preferences."""
    __tablename__ = "user_settings"

    id = Column(Integer, primary_key=True, autoincrement=True)
    key = Column(String(100), unique=True, nullable=False)
    value = Column(Text, nullable=True)
    updated_at = Column(DateTime, default=_utcnow, onupdate=_utcnow)


# ═══════════════════════════════════════════════════════════════════
# Account Mapping Cache
# ═══════════════════════════════════════════════════════════════════

class AccountMapping(Base):
    """
    Cached account-name → audit-category mappings.

    Seeded from account_grouping_labels.csv at startup, then grows
    organically as the LLM classifies new accounts from uploaded trial
    balances.  There is no hard limit on the number of entries.
    """
    __tablename__ = "account_mappings"

    normalized_name = Column(String(500), primary_key=True)   # strip().lower()
    display_name    = Column(String(500), nullable=False)      # original casing
    mapped_to       = Column(String(100), nullable=False)      # audit category
    source          = Column(String(20),  default="llm")       # "seed" | "llm"
    hit_count       = Column(Integer,     default=0)
    last_seen_at    = Column(DateTime, default=_utcnow, onupdate=_utcnow)
    created_at      = Column(DateTime, default=_utcnow)


# ═══════════════════════════════════════════════════════════════════
# Saved Audit Report Model
# ═══════════════════════════════════════════════════════════════════

class SavedReport(Base):
    """A persisted audit report with wizard state, draft, and final content."""
    __tablename__ = "saved_reports"

    id = Column(String(36), primary_key=True, default=_new_id)
    company_name = Column(String(255), nullable=False, default="")
    report_type = Column(String(50), nullable=False, default="audit")
    format = Column(String(50), nullable=False, default="big4")
    period_end_date = Column(String(50), nullable=True)
    status = Column(String(20), nullable=False, default="draft")  # draft | final
    wizard_state_json = Column(JSON, nullable=True)
    draft_content = Column(Text, nullable=True)
    final_content = Column(Text, nullable=True)
    created_at = Column(DateTime, default=_utcnow)
    updated_at = Column(DateTime, default=_utcnow, onupdate=_utcnow)


# ═══════════════════════════════════════════════════════════════════
# Audit Template Models
# ═══════════════════════════════════════════════════════════════════

class AuditTemplate(Base):
    """An extracted audit report template tied to a company and audit cycle."""
    __tablename__ = "audit_templates"

    id = Column(String(36), primary_key=True, default=_new_id)
    company_name = Column(String(255), nullable=False)
    audit_date = Column(DateTime, nullable=True)
    document_structure = Column(JSON, nullable=True)
    account_grouping = Column(JSON, nullable=True)
    terminology = Column(JSON, nullable=True)
    formatting_rules = Column(JSON, nullable=True)
    extraction_method = Column(String(100), nullable=True)
    confidence = Column(Float, default=0.0)
    status = Column(String(20), default="draft")  # draft | approved | rejected
    source_filename = Column(String(500), nullable=True)
    created_at = Column(DateTime, default=_utcnow)
    updated_at = Column(DateTime, default=_utcnow, onupdate=_utcnow)

    sections = relationship(
        "TemplateSection", back_populates="template", cascade="all, delete-orphan"
    )


class TemplateSection(Base):
    """An individual section within an audit template."""
    __tablename__ = "template_sections"

    section_id = Column(String(36), primary_key=True, default=_new_id)
    template_id = Column(String(36), ForeignKey("audit_templates.id"), nullable=False)
    title = Column(String(500), nullable=False)
    level = Column(Integer, default=1)
    start_page = Column(Integer, nullable=True)
    position = Column(Integer, default=0)
    content_type = Column(String(50), nullable=True)  # text | table | notes
    table_structure = Column(JSON, nullable=True)
    accounts = Column(JSON, nullable=True)

    template = relationship("AuditTemplate", back_populates="sections")


# ═══════════════════════════════════════════════════════════════════
# Cross-Session Memory
# ═══════════════════════════════════════════════════════════════════

class UserMemory(Base):
    """Persistent facts extracted from conversations for cross-session memory."""
    __tablename__ = "user_memory"

    id = Column(String(36), primary_key=True, default=_new_id)
    user_id = Column(String(50), nullable=False, default="default")
    key = Column(String(100), nullable=False)
    value = Column(String(500), nullable=False)
    confidence = Column(Float, default=1.0)
    source_conversation_id = Column(String(36), nullable=True)
    created_at = Column(DateTime, default=_utcnow)
    updated_at = Column(DateTime, default=_utcnow, onupdate=_utcnow)
