directories:
  output: dist-electron
  buildResources: build
appId: com.eracorp.accountinglegalchatbot
productName: LegalAcct AI
files:
  - filter:
      - main.js
      - preload.js
      - ../frontend/dist/**
win:
  target: dir
  icon: ../frontend/public/favicon.ico
electronVersion: 31.7.7
